=== prateek-dhanker/Distributed-Computing/Exp4/cricket.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Define the complex type for a contact -->
    <xs:complexType name="playerType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="team" type="xs:string"/>
            <xs:element name="country" type="xs:string"/>
            <xs:element name="role" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Define the root element and its type -->
    <xs:element name="IPL">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="player" type="playerType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== prateek-dhanker/Distributed-Computing/Exp4/cricket.xml
<?xml version="1.0" encoding="UTF-8"?>
<IPL xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cricket.xsd">

    <player>
        <name>MS Dhoni</name>
        <team>CSK</team>
        <country>India</country>
        <role>Batter</role>
    </player>

    <player>
        <name>Virat Kohli</name>
        <team>RCB</team>
        <country>India</country>
        <role>Batter</role>
    </player>

    <player>
        <name>Bumrah</name>
        <team>MI</team>
        <country>India</country>
        <role>Bowler</role>
    </player>

    

</IPL>
